以下の各関数 f3 から f12 までを実行すると何が出力されるか予想し実際に確認しなさい。
またその理由を 2、3 行のテキスト、図のいずれかまたは両方で説明しなさい。テキスト・図は f1 の解答例を参考にしなさい。
出題範囲: 13.2

# 予想

- f3  
  すぐに A が出力され、finally の C が出力される(B は catch できなさそう)

- f4  
  2 秒後に A が出力され、40 が返却される。  
  1000 秒後に B が出力され、100 が返却される。  
  v に何の値が渡されるか？  
  v には 2 つ目に実行された 100 の値が渡されると思うので、最後に 100 が出力される。

- f5
  2 秒後に A が出力され、40 が返却される。：f4 と同じ
  次は Promise が渡されるので、処理は先に進み、v には 40 が渡されると思うので、40 が出力される。  
  その後、B が出力される。

- f6  
  1 秒後に A が出力され、その 1 秒後に B が出力される。  
  そのあと、A が出力されてから、2 秒後に C が出力されるかどうか？  
  2 秒後に出力されそう。

- f7  
  1 行後に A が出力され、その 2 秒後に C が出力される。
  Promise が解決済みなので、B は出力されないと思う。

- f8  
  catch でどのエラーを拾うか？  
  1 秒後に errX を拾い、その後 errY を拾う。
  最後に A が出力される。

- f9  
  最初の then では何をしているか？  
  1 秒後に errY を拾い、最後に A が出力される。

- f10  
  1 秒後に A が出力されて終わりそう。errY は拾われない。理由？

- f11  
  こちらはエラーを catch できそう(なんとなく)

- f12  
  反対にこちらはエラーを catch できなさそう(なんとなく)

# 結果

- f3
  C->A の順で出力され、その後 X の Error が catch された

- f4
  A->B->100 の順で出力された

- f5
  B->A->40 の順で出力された

- f6
  A->B->C の順で出力された

- f7
  A->B->C の順で出力された

- f8
  X->A の順で出力された

- f9
  Y->A の順で出力された

- f10
  A が出力され、その後 Y の 実行時エラーが発生した

  file:///C:/js/JavaScript/ch13/ex02/index.js:29
  throw new Error("Y");
  ^

  Error: Y
  at errY (file:///C:/js/JavaScript/ch13/ex02/index.js:29:9)

  Node.js v20.12.1

- f11
  X が出力された

- f12
  X の 実行時 Error が 発生した
  file:///C:/js/JavaScript/ch13/ex02/index.js:26
  throw new Error("X");
  ^
  Error: X
  at errX (file:///C:/js/JavaScript/ch13/ex02/index.js:26:9)
  at Timeout.\_onTimeout (file:///C:/js/JavaScript/ch13/ex02/index.js:207:22)
  at listOnTimeout (node:internal/timers:573:17)
  at process.processTimers (node:internal/timers:514:7)

  Node.js v20.12.1

# 理由

- f3
  (訳)0 秒待って成功したら A を出力する。A が成功したら、errX を出力する。

  finally が先に実行される理由？
  0 秒後に try の中が実行されるが、先に finally の方が実行され、C が出力される。
  A が実行され、X が実行される。
  例外は catch できないので、B は出力されない。

- f4
  (訳)2 秒待って成功したら A を出力し、40 を返す。前が終わったら 1 秒待って成功したら、B を出力し、100 を返す。前が終わったら return されたものを表示する。

  引数の value は何？40 が入っている？
  試しに console.log(value)したら 40 が出力された

  2 秒後に 1 つ目の then が実行されるので、A が出力。
  その際に 40 が return される。
  その後、2 つ目の then が実行され、1 秒後に B が出力され、100 が return され、最後に 100 が出力される。
  40 は 100 で上書きされる。

- f5
  2 つ目の then の中は Promise なので、前の処理の影響を受けないので、先に実行され、1 秒待って B が出力される。
  2 秒待って成功したら A を出力し、40 を返す。次の then はすでに終了済みなので、log(v)には 40 が出力される。

- f6
  Promise は then()を呼び出すたびに新しい Promise が返されている(p.387)

  1 つ目の Promise でも複数 then が呼び出しできるので(?)
  1 秒後に A が出力、1 秒後に B が出力、2 秒後に C が出力される。

- f7
  まずは 1 つ目の then が実行されるので、A が出力される。
  2 秒後に p は解決しているが、呼び出し可能(？)：まだ満たされていない状態(p.389)なので、そのまま B と C が出力される。

- f8
  (訳)1 秒待って成功したら errX を throw する。1 つ目の then が成功したら 2 つ目の then を実行する。前で Error が throw されたら catch する。処理の結果にかかわらず最後に finally を実行する。

  1 つ目の then で X の Error が throw されるので、catch されて X が出力される。
  1 つ目の then が成功していないので、2 つ目の then は実行されない。
  finally は必ず実行されるので A が出力される。

- f9
  (訳)1 秒待って成功したら 1 つ目の then を実行する。1 つ目の then が成功したら 2 つ目の then を実行する。前で Error が throw されたら catch する。処理の結果にかかわらず最後に finally を実行する。

  1 つ目の then は実行されるが、特に出力がないので、そのまま次の then が実行され、Y の Error が catch される。
  finally は必ず実行されるので A が出力される。

- f10
  (訳)1 秒待って成功したら 1 つ目の then を実行する。1 つ目の then が成功したら 2 つ目の then を実行する。引数が 2 つなので、前の then が成功したら errY を実行し、失敗したら 2 つ目の log 出力が行われる。
  処理の結果にかかわらず finally を実行する。

  1 つ目の then は成功するので、errY が実行される。しかし、実行時エラーが発生。finally の A が出力される。

- f11
  new Promise 内でエラーを throw すると catch されるので、X が出力される

- f12
  コールバック関数で throw した場合には、戻り先がない(？)ので、実行時エラーが発生。
