以下の各関数を実行すると何が出力されるか予想し実際に確認しなさい。
またその理由を 2、3 行のテキスト、図のいずれかまたは両方で説明しなさい。テキスト・図は問題 13.2 を参考にしなさい。
出題範囲: 13.3

# 予想

- h1  
  C → 　 B → 　 A の順で 1 秒ずつ後で出力される

- h2  
  errX は実行されず、catch されたエラーが出力される

- h3  
  errX が実行され、そのあと catch されたエラーが出力される

- h4  
  2 秒後に errX が出力され、その 1 秒後に errY が出力される  
  catch ではエラーは捕まえられなさそう

# 結果

- h1
  3 秒後に A、その 2 秒後に B、その 1 秒後に C が出力された

- h2
  X が出力された

- h3
  X の 実行時エラーが出力された

- h4
  Y の 実行時エラーが出力された

# 理由

- h1
  await は解決するまで次の処理が行われないので先頭から順に実行された(予想では並行実行だったが、await は解決しないと次に進まない)

- h2
  Promise の引数が、関数呼び出しの場合は catch されるので、X の出力のみ。

- h3
  Promise の引数が、async function の場合は h2 と異なり、catch されずに実行時エラー

- h4
  待つ秒数が 1 秒なので、errY が先に実行されるが、エラーは catch できないので、 Y の実行時エラーが発生する。

  先の await p1 の方が先に実行されないのか？
  読み込みの時点で実行されるから？
  await p1 の時点ではすでに解決されている？
